### ISSUE TITLE
ImageNet 21K list of concepts

### ISSUE THREAD

**Issue by EricElmoznino** [bsorsch/geometry_fewshot_learning#1]
Hey, love the work! In the paper, you said "A full list of the 1, 000 concepts used in our evaluation set is available at
github.com/bsorsch/geometry_fewshot_learning". I haven't been able to find this list in the repository and the code seems to reference a directory saved locally on your machine. Would it be possible to add this list to the repo?

**Comment by bsorsch-zz** [comment]
Yes of course! I've just included a list of the 1k evaluation class names in the repo, as well as their corresponding wordnet IDs (wnids). Thank you for letting me know!
